skillset = {
			'CS': [
					'java', 
					'python', 
					'c++',
					'c#', 
					'lisp',
					'node.js', 
					'javascript', 
					'machine learning', 
					'AI',
					'artificial intelligence', 
					'data modeling', 
					'jquery', 
					'ruby',
					'rails',
					'asp.net'
					'graph theory',
					'business analytics', 
					'sysadmin', 
					'linux', 
					'hadoop', 
					'big data',
					'mongodb', 
					'pgsql', 
					'postgres',
					'postgresql',
					'sql',
					'mssql',
					'mysql',
					'sqllite',
					'mariadb',
					'database',
					'clojure',
					'lua',
					'scala',
					'ubuntu',
					'android',
					'iphone',
					'web applications',
					'flask',
					'django',
					'excel',
					'tableau',
					'cassandra',
					'coffeescript',
					'.net',
					'html',
					'css',
					'api',
					'lucene',
					'osx',
					'git',
					'devops',
					'powershell',
					'REST',
					'sql-server',
					'aws',
					'php',
					'd3.js',
					'angular.js',
					'golang',
					'html5',
					'nosql',
					'vb.net',
					'nix',
					'web services',
					'objective c',
					'software testing',
					'selenium',
					'azure',
					'SOAP',
					'ajax',
					'apache',
					'SAAS',
					'r language',
					'cloud computing',
					'reactjs',
					'css3',
					'scss',
					'vmware',
					'software qa',
					'mapreduce',
					'map-reduce',
					'distributed computing',
					'database administration',
					'db admin',
					'db administrator',
					'sysadmin',
					'systems administrator',
					'redis',
					'hive',
					'hive pig',
					],

			'DESIGN': [
					'UI', 
					'UX', 
					'Photoshop', 
					'css', 
					'wire frames', 
					'dashboard', 
					'visualization',
					'user interface',
					'user interaction',
					'user experience',
					'html',
					'html5',
					'marionette',
					'axure',
					'responsive design',
					'css3',
					'opengl',
					'web designer',
					'front end developer',
					'front end designer',
					'frontend designer',
					'frontend developer',
			],

			'ACCOUNTS': [
					'finance',
					'accounts',
					'accounting',
					'tax preparation',
					'invoice reconciliation',
					'invoicing',
					'payables',
					'receivables',
					'check cashing',
					'financial audit',
					'investment banking',
					'portfolio management',
					'credit analysis',
					'loans',
					'business taxation',
					'taxation',
					'consumer banking',
					'retail banking',
					'stocks',
					'hedge funds',
					'compliance',
					'credit risk',
					'credit risk management',
					'profit',
					'credit card',
					'closing services',
					'banking',
					'bonds',
					'stocks bonds',
					'credit union',
					'financial management',
					'taxation law',
					'tax services',
					'hedging',
					'derivatives',
			],

			'HUMAN_RESOURCE': [
					'payroll',
					'recruitment',
					'interviewing skills',
					'employee tests',
					'employee training',
					'office administration',
					'hr management',
					'human resource management',
					'benefits management',
					'benefits analyst',
					'employee management',
					'employee records management',
			],

			'DATA_SCIENCE': [
					'probabilistic models',
					'neural networks',
					'graphical models',
					'hidden markov models',
					'random forest',
					'linear regression',
					'support vector machine',
					'statistical modeling',
					'algorithms',
					'forecasting',
					'time series',
					'predictive modeling',
					'predictive analytics',
					'data visualization',
					'data analysis',
					'data mining',
					'histograms',
					'linear programming',
					'numerical optimization',
					'bayesian networks',
					'naive bayes',
					'decision trees',
					'algorithmic optimization',
					'number theory',
					'differential calculus',
					'data analytics',
			],
		'ELECTRICAL': [
			'power systems',
			'electrical engineering',
			'electrical circuits',
			'signal processing',
			'transistors',
			'capacitors',
			'transformers',
			'wiring',
			'hvac',
			'control systems',
			'power grids',
			'telecommunications',
			'microcontrollers',
			'IEEE',
			'instrumentation',
			'transmission lines',
			'power lines',
			'antenna',
			'electrodynamics',
			'fuzzy control',
			'PID controller',
			'electrical network',
			'DC systems',
			'AC systems',
			'two-phase systems',
			'three-phase systems',
			'VAR compensator',
			'electric motors',
			'electricity',
			'smart grid',
			'quantization',
			'sampling',
			'digital signal processing',
			'dsp systems',
			'fft',
			'oscilloscope',

		],

		'TEACHING': [
			'courses',
			'exams',
			'course work',
			'instructor',
			'teacher',
			'school',
			'college',
			'university',
			'professor',
			'doctorate',
			'post graduate',
			'learning programs',
			'teaching skills',
		],

		'NURSING': [
			'RN staff', 
			'BSN medical', 
			'nurse practitioner', 
			'critical care', 
			'I.V. certified', 
			'CPR certified', 
			'pediatrics', 
			'ventilator management', 
			'chemotherapy administration', 
			'oncology', 
			'trauma', 
			'clinical research', 
			'case management', 
			'substance abuse', 
			'phlebotomy', 
			'community outreach', 
			'managed care',
			'physiotherapy',
			'patient management',
			'hospital management',
			'nursing',
			'physicians'
			],

		'PLUMBING': [
			'plumbing',
			'plumbing supplies',
			'shower plumbing',
			'heating system',
			'hvac systems',
			'plumbing fixtures',
			'kitchen plumbing',
			'sinks',
			'bathtub',
			'kitchen',
			'toilet',
			'water pipelines',
			'faucets',
			'tools plumbing',
			'pipe plumbing',
			'fittings',
			'ferguson',
			'brass plumbing',
			'taps plumbing',
			'water tanks',
			'oil tanks'
		]
}
