skillset = {
			'CS': [
					'java', 
					'python', 
					'c++',
					'c#', 
					'lisp',
					'node.js', 
					'javascript', 
					'machine learning', 
					'AI',
					'artificial intelligence', 
					'data modeling', 
					'jquery', 
					'ruby',
					'rails',
					'asp.net'
					'graph theory',
					'business analytics', 
					'sysadmin', 
					'linux', 
					'hadoop', 
					'big data',
					'mongodb', 
					'pgsql', 
					'postgres',
					'postgresql',
					'sql',
					'mssql',
					'mysql',
					'sqllite',
					'mariadb',
					'database',
					'clojure',
					'lua',
					'scala',
					'ubuntu',
					'android',
					'iphone',
					'web applications',
					'flask',
					'django',
			
					'tableau',
					'cassandra',
					'coffeescript',
					'.net',
					'html',
					'css',
					'api',
					'lucene',
					'osx',
					'git',
					'devops',
					'powershell',
					'REST',
					'sql-server',
					'aws',
					'php',
					'd3.js',
					'angular.js',
					'golang',
					'html5',
					'nosql',
					'vb.net',
					'nix',
					'web services',
					'objective c',
					'software testing',
					'selenium',
					'azure',
					'SOAP',
					'ajax',
					'apache',
					'SAAS',
					'r language',
					'cloud computing',
					'reactjs',
					'css3',
					'scss',
					'vmware',
					'software qa',
					'mapreduce',
					'map-reduce',
					'distributed computing',
					'database administration',
					'db admin',
					'db administrator',
					'sysadmin',
					'systems administrator',
					'redis',
					'hive',
					'hive pig',
					],

			'DESIGN': [
					'UI', 
					'UX', 
					'Photoshop', 
					'css', 
					'wire frames', 
					'dashboard', 
					'visualization',
					'user interface',
					'user interaction',
					'user experience',
					'html',
					'html5',
					'marionette',
					'axure',
					'responsive design',
					'css3',
					'opengl',
					'web designer',
					'front end developer',
					'front end designer',
					'frontend designer',
					'frontend developer',
			],

			'ACCOUNTS': [
					'finance',
					'accounts',
					'accounting',
					'tax preparation',
					'invoice reconciliation',
					'invoicing',
					'payables',
					'receivables',
					'check cashing',
					'financial audit',
					'investment banking',
					'portfolio management',
					'credit analysis',
					'loans',
					'business taxation',
					'taxation',
					'consumer banking',
					'retail banking',
					'stocks',
					'hedge funds',
					'compliance',
					'credit risk',
					'credit risk management',
					'profit',
					'credit card',
					'closing services',
					'banking',
					'bonds',
					'stocks bonds',
					'credit union',
					'financial management',
					'taxation law',
					'tax services',
					'hedging',
					'derivatives',
			],

			'HUMAN_RESOURCE': [
					'payroll',
					'recruitment',
					'interviewing skills',
					'employee tests',
					'employee training',
					'office administration',
					'hr management',
					'human resource management',
					'benefits management',
					'benefits analyst',
					'employee management',
					'employee records management',
			],

			'DATA_SCIENCE': [
					'probabilistic models',
					'neural networks',
					'graphical models',
					'hidden markov models',
					'random forest',
					'linear regression',
					'support vector machine',
					'statistical modeling',
					'algorithms',
					'forecasting',
					'time series',
					'predictive modeling',
					'predictive analytics',
					'data visualization',
					'data analysis',
					'data mining',
					'histograms',
					'linear programming',
					'numerical optimization',
					'bayesian networks',
					'naive bayes',
					'decision trees',
					'algorithmic optimization',
					'number theory',
					'differential calculus',
					'data analytics',
			],
		'ELECTRICAL': [
			'power systems',
			'electrical engineering',
			'electrical circuits',
			'signal processing',
			'transistors',
			'capacitors',
			'transformers',
			'wiring',
			'hvac',
			'control systems',
			'power grids',
			'telecommunications',
			'microcontrollers',
			'IEEE',
			'instrumentation',
			'transmission lines',
			'power lines',
			'antenna',
			'electrodynamics',
			'fuzzy control',
			'PID controller',
			'electrical network',
			'DC systems',
			'AC systems',
			'two-phase systems',
			'three-phase systems',
			'VAR compensator',
			'electric motors',
			'electricity',
			'smart grid',
			'quantization',
			'sampling',
			'digital signal processing',
			'dsp systems',
			'fft',
			'oscilloscope',

		],

		'TEACHING': [
			'courses',
			'exams',
			'course work',
			'instructor',
			'teacher',
			'school',
			'college',
			'university',
			'professor',
			'doctorate',
			'post graduate',
			'learning programs',
			'teaching skills',
		],

		'NURSING': [
			'RN staff', 
			'BSN medical', 
			'nurse practitioner', 
			'critical care', 
			'I.V. certified', 
			'CPR certified', 
			'pediatrics', 
			'ventilator management', 
			'chemotherapy administration', 
			'oncology', 
			'trauma', 
			'clinical research', 
			'case management', 
			'substance abuse', 
			'phlebotomy', 
			'community outreach', 
			'managed care',
			'physiotherapy',
			'patient management',
			'hospital management',
			'nursing',
			'physicians'
			],

		'PLUMBING': [
			'plumbing',
			'plumbing supplies',
			'shower plumbing',
			'heating system',
			'hvac systems',
			'plumbing fixtures',
			'kitchen plumbing',
			'sinks',
			'bathtub',
			'kitchen',
			'toilet',
			'water pipelines',
			'faucets',
			'tools plumbing',
			'pipe plumbing',
			'fittings',
			'ferguson',
			'brass plumbing',
			'taps plumbing',
			'water tanks',
			'oil tanks'
		],

'TELEMARKETER':  [
	'customer relationship management software',
	'CRM systems', 
	'salesforce',
	'infusionsoft',
	'Pardot',
	'Zendesk',
	'predictive dialers',
	'call recording systems',
	'call center software',
	'customer service',
	'speaking',
	'persuasion',
	'active listening',
	'fluent english',
	'oral comprehension',
	'reading from script',
	'answer customer questions',
	'record information',
	'professional demeanor',
	'campaigns',
	'telemarketing',
],

'HUMAN_RESOURCES_SPECIALIST': [
	'Human Resource Management Systems',
	'HRMS',
	'Workday',
	'Taleo',
	'Greenhouse',
	'BambooHR',
	'Zenefits',
	'Kronos',
	'Ultipro',
	'Bullhorn',
	'Linkedin',
	'Google',
	'SAS',
	'IBM Cognos',
	'talent acquisition',
	'interviewing',
	'regulations',
	'Americans with Disabilities Act',
	'ADA',
	'policy compliance',
	'OSHA',
	'assessment software',
	'personnel resources',
	'recruiting',
	'recruitment',
	'staffing',
	'organizational development',
	'employee development',
	'organizational management',
	'industrial psychology',
	'organizational psychology',
	'benefits analyst',
	'benefits',
	'payroll',
],


'SALES_ENGINEER': [
	'team collaboration',
	'gather customer requirements',
	'requirements survey',
	'analytical skills',
	'UNIX',
	'Linux',
	'AWS',
	'SAP',
	'Hyperion',
	'Oracle',
	'enterprise content management',
	'systems analysis',
	'Github',
	'Python',
	'Perl',
	'SQL',
	'PHP',
	'SAML',
	'REST',
	'SOAP',
	'technical relationship',
	'customer presentation',
	'technical presentation',
	'proof of concept',
	'trusted advisor',
	'thought leadership',
	'technical expertise',
	'sharepoint',
	'product demo',
	'certification',
	'architecture',
	'troubleshooting',
],


'FINANCIAL_ANALYST': [
	'spreadsheets',
	'Bloomberg',
	'Delphi software',
	'Wolfram Research Mathematica UnRisk Pricing Engine',
	'DailyVest Investment Personalization Platform',
	'LexisNexis software',
	'TradeTools Monthly U.S. Economic Database',
	'Ward Systems Group NeuroShell Trader',
	'accounts',
	'risk',
	'risk analysis',
	'economics',
	'statistics',
	'critical thinking',
	'data analysis',
	'data gathering',
	'investment recommendations',
	'investment analysis',
	'market analysis',
	'P&L',
	'CAPEX',
	'OPEX',
	'accounting',
	'planning',
	'budgeting',
	'variance analysis',
	'forecasting',
	'sensitivity analysis'
	'financial statements'
],


'SUPPLY_CHAIN_ANALYST': [
	'ERP software',
	'SAP',
	'Oracle',
	'Hyperion',
	'3PL Central',
	'Cadre Technologies Accuplus Integrated Distribution Logistics System',
	'Four Soft 4S VisiLog',
	'Oracle E-Business Suite Logistics',
	'spreadsheets',
	'SQL',
	'Six Sigma'
	'APICS CPIM'
	'Microsoft Project', 
	'Microsoft SharePoint software',
	'Oracle Primavera Enterprise Project Portfolio Management software',
	'data analysis',
	'statistics',
	'critical thinking',
	'data gathering',
	'inventory analysis',
	'vendor management',
	'vendor relations',
	'production schedule optimization',
	'inventory level optimization',
	'raw material inventory management',
	'material flow parameters',
	'capacity planning',
	'reduce lead times',
	'demand planning',
	'data collection',
],


'CUSTOMER_SERVICE_REPRESENTATIVE': [
	'ERP software',
	'SAP',
	'Intuit',
	'Oracle JD Edwards EnterpriseOne',
	'customer relationship management software',
	'CRM systems', 
	'Avidian Technologies Prophet', 
	'Salesforce.com Salesforce CRM', 
	'SSA Global software', 
	'Telemation e-CRM',
	'spreadsheet',
	'predictive dialers',
	'call recording systems',
	'call center software',
	'influencing others',
	'customer service',
	'speaking',
	'persuasion',
	'active listening',
	'social perceptiveness',
	'fluent english',
	'oral comprehension',
	'reading from scripts',
	'answer customer questions',
	'record information',
],


'MARKETING_MANAGER': [
	'statistics',
	'statistical analysis',
	'marketing strategy',
	'market analysis',
	'advertising',
	'promotion',
	'pricing strategies',
	'salesforce.com',
	'ClearEDGE software',
	'adobe',
	'photoshop',
	'customer survey',
	'Marketo',
	'CRM software',
	'KPI',
	'content collateral',
	'channel support',
	'critical thinking',
	'communication skills',
	'data collection',
	'sales forecasting',
	'Nedstat Sitestat',
	'SAS software',
	'Google Adwords',
	'Facebook',
	'Bing Ads',
	'SEO',
	'SEM',
	'competitive intelligence',
	'competitive analysis',
],


'ACCOUNT_MANAGER_SALES_REPRESENTATIVE': [
	'account strategy',
	'Go To Market model',
	'salesforce.com',
	'financial statements',
	'financial analysis',
	'client relationship',
	'P&L',
	'cash flow',
	'strategic thinking',
	'financial acumen',
	'Service Level Agreement',
	'spreadsheet',
	'sales',
	'contract negotiation',
	'partnering',
	'persuasion',
	'communication',
	'social skills',
	'people skills',
	'interpersonal',
	'presenting',
	'customer presentation',
	'presentation',
	'public speaking',
	'written skills',
	'critical thinking',
	'customer service',
	'CRM',
	'SAP',
	'solution sale',
	'channels',
	'data visualization',
	'industry expertise',
	'monetization',
	'team building',
	'leadership',
	'implementation strategy',
	'competitive intelligence',
	'competitive analysis',
	'self-motivated',
	'under pressure',
	'goal oriented',
	'quota',
],

'UNDERWRITER': [
	'risk analysis',
	'risk exposure',
	'pricing structure',
	'terms & conditions',
	'multi-headed risk review',
	'compliance',
	'appraisal review',
	'loan review',
	'agency relationship',
	'INS',
	'AU',
	'rating plans',
	'state insurance laws',
	'federal insurance laws',
	'spreadsheet',
	'business development',
	'Anodas Software Limited Phoenix',
	'Consilience Software Maven Insurance Automation Suite',
	'SIS SEMCI PARTNER', 
	'Skywire Software InsBridge',
	'Fannie Mae Desktop Underwriter',
	'Fiserv Advanced Underwriting',
	'RGA Facultative Application Console', 
	'Valen Technologies Risk Manager',
	'Assess financial status of clients',
	'Authorize financial actions',
	'Explain regulations, policies, or procedures',
	'Verify accuracy of records',
	'Assess risks to business operations',
],


'PROJECT_MANAGER': [
	'budget management', 
	'schedule management', 
	'project scope management',
	'project financial management',
	'funding',
	'scheduling',
	'staffing',
	'project milestones',
	'project deliverables', 
	'work breakdown structure (WBS)',
	'Microsoft Project',
	'Microsoft SharePoint software',
	'Wrike',
	'Zoho Projects',
	'mindmap',
	'negotiation',
	'persuasion',
	'customer requirements',
	'delivery goal alignment',
	'manage execution',
	'manage stakeholders',
	'project lifecycle management',
	'project plan',
	'forecasts',
	'variance',
	'backlog',
	'completion rate',
	'issue resolution',
	'PMP',
	'critical thinking',
	'problem solving',
	'interpersonal skills',
	'strategic planning',
	'tactical management',
	],

'CLINICAL_PSYCHOLOGIST': [
	'educational development',
	'psychology',
	'human behaviour',
	'mental therapy',
	'hypnosis',
	'counseling humans',
	'psychotherapy',
	'behavior modification',
	'stress reduction therapy',
	'psychodrama',
	'play therapy',
	'diagnose disorders',
	'behavioral issues',
	'biofeedback',
	'ICANotes',
	'Anasazi Software Client Data System',
	'emotional support',
	'psychological tests',
	'mental health',
	'neural disorders',
	'psychological disorders',
	],
'SCHOOL_PSYCHOLOGIST': [
	'student counseling',
	'conflict resolution',
	'Centris Group IEP Direct',
	'Vision Management Consulting IEP PlaNET',
	'Xperts iep.online',
	'counsel children',
	'psychological tests',
	'interpret students',
	'psychological research methods',
	'mental rehabilitation',
	'group behavior',
	],
'TELEPHONE_OPERATOR': [
	'PBX equipment',
	'telephone switchboards',
	'voice equipment',
	'customer data',
	'greeting customers telephone',
	'secure voice equipment',
	'switching system',
	'broadcasting telephone',
	'signal light switchboard',
	'operate telephone',
	'long distance call'
]

}
